### ISSUE TITLE
Step 4 Yarn: .env.example to .env client id and secret

### ISSUE THREAD

**Issue by DatBoiiiiBryan** [bddvlpr/bad-vrc-osc#2]
im unsure what to do at this step if anyone could help me out thatd be fantastic.

**Comment by bddvlpr** [comment]
Enable hidden files in your explorer. You should copy the invisible `.env.example` file to `.env` and fill in said parameters in that file.

**Comment by bddvlpr** [comment]
Marking issue as solved.
